---
services:
  thewall:
    container_name: thewall
    image: ghcr.io/coder0x6675/thewall:latest
    restart: unless-stopped
    healthcheck:
      test: wget -q -O /dev/null -t 1 http://127.0.0.1:3000/
    ports:
      - '3000:3000'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data:/data'
